<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TagsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('tags')->delete();

        // Seed tags with: name, description
        // Note that the original tags do not have a description, so we add them here in a seeder.
        \DB::table('tags')->insert([
            0   => [
                'id'                  => 1,
                'is_published'        => 1,
                'name'                => 'JOTA-JOTI',
                'description'         => 'Jamboree On The Air en Jamboree On The Internet - het wereldwijde scout radio- en internet-evenement waarbij scouts over de hele wereld met elkaar in contact komen',
                'special_interest_at' => '2000-10-21',
            ],
            1   => [
                'id'                  => 2,
                'is_published'        => 1,
                'name'                => 'Online',
                'description'         => 'Activiteiten die digitaal of via internet kunnen worden uitgevoerd',
                'special_interest_at' => null,
            ],
            2   => [
                'id'                  => 3,
                'is_published'        => 1,
                'name'                => '1,5 meter',
                'description'         => 'Activiteiten die geschikt zijn voor het houden van 1,5 meter afstand tijdens de coronaperiode',
                'special_interest_at' => null,
            ],
            3   => [
                'id'                  => 4,
                'is_published'        => 1,
                'name'                => 'Waterscouting',
                'description'         => 'Alle activiteiten die te maken hebben met het water en varen binnen Scouting',
                'special_interest_at' => null,
            ],
            4   => [
                'id'                  => 5,
                'is_published'        => 1,
                'name'                => 'Waterspelen',
                'description'         => 'Spellen en activiteiten die in of met water worden gespeeld',
                'special_interest_at' => null,
            ],
            5   => [
                'id'                  => 6,
                'is_published'        => 1,
                'name'                => 'CWO',
                'description'         => 'Commissie Watersport Opleidingen - het officiële diplomasysteem voor watersportactiviteiten',
                'special_interest_at' => null,
            ],
            6   => [
                'id'                  => 7,
                'is_published'        => 1,
                'name'                => 'CWO Kielboot',
                'description'         => 'Opleidingen en activiteiten gericht op het varen met een kielboot volgens CWO-richtlijnen',
                'special_interest_at' => null,
            ],
            7   => [
                'id'                  => 8,
                'is_published'        => 1,
                'name'                => 'CWO Roeiboot',
                'description'         => 'Opleidingen en activiteiten gericht op het roeien volgens CWO-richtlijnen',
                'special_interest_at' => null,
            ],
            8   => [
                'id'                  => 9,
                'is_published'        => 1,
                'name'                => 'CWO Sloep/Motorvlet',
                'description'         => 'Opleidingen en activiteiten gericht op het varen met een sloep of motorvlet volgens CWO-richtlijnen',
                'special_interest_at' => null,
            ],
            9   => [
                'id'                  => 10,
                'is_published'        => 1,
                'name'                => 'CWO Buitenboord Motor',
                'description'         => 'Opleidingen en activiteiten gericht op het varen met buitenboordmotor volgens CWO-richtlijnen',
                'special_interest_at' => null,
            ],
            10  => [
                'id'                  => 11,
                'is_published'        => 1,
                'name'                => 'Binnenvaart',
                'description'         => 'Activiteiten en kennis gerelateerd aan de Nederlandse binnenvaart',
                'special_interest_at' => null,
            ],
            11  => [
                'id'                  => 12,
                'is_published'        => 1,
                'name'                => 'Memorie',
                'description'         => 'Geheugen- en concentratiespellen voor verschillende leeftijdsgroepen',
                'special_interest_at' => null,
            ],
            12  => [
                'id'                  => 13,
                'is_published'        => 1,
                'name'                => 'Kimspelen',
                'description'         => 'Observatie- en geheugenspellen waarbij voorwerpen onthouden of gevonden moeten worden',
                'special_interest_at' => null,
            ],
            13  => [
                'id'                  => 14,
                'is_published'        => 1,
                'name'                => 'Balspelen',
                'description'         => 'Alle sporten en spellen waarbij een bal centraal staat',
                'special_interest_at' => null,
            ],
            14  => [
                'id'                  => 15,
                'is_published'        => 1,
                'name'                => 'Handel en Smokkelspelen',
                'description'         => 'Actieve spellen waarbij het verhandelen of smokkelen van items centraal staat',
                'special_interest_at' => null,
            ],
            15  => [
                'id'                  => 16,
                'is_published'        => 1,
                'name'                => 'China',
                'description'         => 'Activiteiten en spellen gerelateerd aan de Chinese cultuur en tradities',
                'special_interest_at' => null,
            ],
            16  => [
                'id'                  => 17,
                'is_published'        => 1,
                'name'                => 'Avondspelen en Nachtspelen',
                'description'         => 'Spellen en activiteiten die specifiek in de avond of nacht worden gespeeld',
                'special_interest_at' => null,
            ],
            17  => [
                'id'                  => 18,
                'is_published'        => 1,
                'name'                => 'Modderdag',
                'description'         => 'Activiteiten waarbij spelen met modder centraal staat, vaak gekoppeld aan de internationale Modderdag',
                'special_interest_at' => '2000-06-29',
            ],
            18  => [
                'id'                  => 19,
                'is_published'        => 1,
                'name'                => 'Sustainable Development Goals (SDG)',
                'description'         => 'Activiteiten gericht op de duurzame ontwikkelingsdoelen van de Verenigde Naties',
                'special_interest_at' => null,
            ],
            19  => [
                'id'                  => 20,
                'is_published'        => 1,
                'name'                => 'Duurzame ontwikkelingsdoel 15 Leven op het land',
                'description'         => 'Activiteiten gericht op het beschermen, herstellen en duurzaam gebruik van ecosystemen op het land',
                'special_interest_at' => null,
            ],
            20  => [
                'id'                  => 21,
                'is_published'        => 1,
                'name'                => 'Kampactiviteiten',
                'description'         => 'Alle activiteiten die specifiek tijdens kampen kunnen worden uitgevoerd',
                'special_interest_at' => null,
            ],
            21  => [
                'id'                  => 22,
                'is_published'        => 1,
                'name'                => 'EHBO',
                'description'         => 'Eerste Hulp Bij Ongelukken - activiteiten en oefeningen om eerste hulp te leren verlenen',
                'special_interest_at' => null,
            ],
            22  => [
                'id'                  => 23,
                'is_published'        => 1,
                'name'                => '4 en 5 Mei',
                'description'         => 'Activiteiten rond Dodenherdenking en Bevrijdingsdag, gericht op herdenken en vieren van vrijheid',
                'special_interest_at' => '2000-05-05',
            ],
            23  => [
                'id'                  => 24,
                'is_published'        => 1,
                'name'                => 'Duurzame ontwikkelingsdoel 16 Vrede, justitie en sterke publieke diensten',
                'description'         => 'Activiteiten gericht op het bevorderen van vreedzame en inclusieve samenlevingen',
                'special_interest_at' => null,
            ],
            24  => [
                'id'                  => 25,
                'is_published'        => 1,
                'name'                => 'Twister',
                'description'         => 'Activiteiten gebaseerd op het bekende behendigheidsspel Twister',
                'special_interest_at' => null,
            ],
            25  => [
                'id'                  => 26,
                'is_published'        => 1,
                'name'                => 'Duurzame ontwikkelingsdoel 13 Klimaatactie',
                'description'         => 'Activiteiten gericht op klimaatverandering en de aanpak daarvan',
                'special_interest_at' => null,
            ],
            26  => [
                'id'                  => 27,
                'is_published'        => 1,
                'name'                => 'Duurzame ontwikkelingsdoel 14 Leven in het water',
                'description'         => 'Activiteiten gericht op het beschermen en duurzaam gebruiken van oceanen en zeeën',
                'special_interest_at' => null,
            ],
            27  => [
                'id'                  => 28,
                'is_published'        => 1,
                'name'                => 'Pasen',
                'description'         => 'Activiteiten en spellen rond het paasfeest',
                'special_interest_at' => '2000-04-10',
            ],
            28  => [
                'id'                  => 29,
                'is_published'        => 1,
                'name'                => 'Scout Scarf Day',
                'description'         => 'Activiteiten rond de internationale dag waarop scouts hun das dragen om scouting te promoten',
                'special_interest_at' => '2000-08-01',
            ],
            29  => [
                'id'                  => 30,
                'is_published'        => 1,
                'name'                => 'Luchtscouting',
                'description'         => 'Activiteiten gericht op luchtvaart en vliegen binnen scouting',
                'special_interest_at' => '2000-12-07',
            ],
            30  => [
                'id'                  => 31,
                'is_published'        => 1,
                'name'                => 'Nacht van de Nacht',
                'description'         => 'Activiteiten tijdens de jaarlijkse campagne voor het donker van de nacht en tegen lichtvervuiling',
                'special_interest_at' => '2000-10-26',
            ],
            31  => [
                'id'                  => 32,
                'is_published'        => 1,
                'name'                => 'Minipionieren',
                'description'         => 'Kleine pioniersprojecten geschikt voor jongere scouts',
                'special_interest_at' => null,
            ],
            32  => [
                'id'                  => 33,
                'is_published'        => 1,
                'name'                => 'Duurzame ontwikkelingsdoel 12 Verantwoorde consumptie en productie',
                'description'         => 'Activiteiten gericht op duurzame consumptie- en productiepatronen',
                'special_interest_at' => null,
            ],
            33  => [
                'id'                  => 34,
                'is_published'        => 1,
                'name'                => 'Sinterklaas',
                'description'         => 'Activiteiten en spellen rond het sinterklaasfeest',
                'special_interest_at' => '2000-12-05',
            ],
            34  => [
                'id'                  => 35,
                'is_published'        => 1,
                'name'                => 'Duurzame ontwikkelingsdoel 4 Kwaliteitsonderwijs',
                'description'         => 'Activiteiten gericht op het bevorderen van kwalitatief goed onderwijs',
                'special_interest_at' => null,
            ],
            35  => [
                'id'                  => 36,
                'is_published'        => 1,
                'name'                => 'Duurzame ontwikkelingsdoel 10  Ongelijkheid verminderen',
                'description'         => 'Activiteiten gericht op het verminderen van ongelijkheid binnen en tussen landen',
                'special_interest_at' => null,
            ],
            36  => [
                'id'                  => 37,
                'is_published'        => 1,
                'name'                => 'Duurzame ontwikkelingsdoel 7 Betaalbare en duurzame energie',
                'description'         => 'Activiteiten gericht op toegang tot betaalbare en duurzame energie voor iedereen',
                'special_interest_at' => null,
            ],
            37  => [
                'id'                  => 38,
                'is_published'        => 1,
                'name'                => 'Tijd voor Avontuur',
                'description'         => 'Uitdagende activiteiten die een beroep doen op avontuurlijke vaardigheden',
                'special_interest_at' => null,
            ],
            38  => [
                'id'                  => 39,
                'is_published'        => 1,
                'name'                => 'Tochttechnieken',
                'description'         => 'Activiteiten gericht op kaartlezen, kompas gebruiken en navigeren',
                'special_interest_at' => null,
            ],
            39  => [
                'id'                  => 40,
                'is_published'        => 1,
                'name'                => 'Natuurwerkdag',
                'description'         => 'Activiteiten gericht op natuurbeheer en natuurbehoud tijdens de nationale natuurwerkdag',
                'special_interest_at' => '2000-11-01',
            ],
            40  => [
                'id'                  => 41,
                'is_published'        => 1,
                'name'                => 'Duurzame ontwikkelingsdoel 5 Gendergelijkheid',
                'description'         => 'Activiteiten gericht op het bereiken van gendergelijkheid en empowerment van vrouwen en meisjes',
                'special_interest_at' => null,
            ],
            41  => [
                'id'                  => 42,
                'is_published'        => 1,
                'name'                => 'Kerst',
                'description'         => 'Activiteiten en spellen rond de kerstperiode',
                'special_interest_at' => '2000-12-24',
            ],
            42  => [
                'id'                  => 43,
                'is_published'        => 1,
                'name'                => 'Vrijwilligers',
                'description'         => 'Activiteiten gericht op en voor vrijwilligers binnen scouting',
                'special_interest_at' => null,
            ],
            43  => [
                'id'                  => 44,
                'is_published'        => 1,
                'name'                => 'Open Dag',
                'description'         => 'Activiteiten geschikt voor het organiseren van een open dag bij de scoutinggroep',
                'special_interest_at' => '2000-09-01',
            ],
            44  => [
                'id'                  => 45,
                'is_published'        => 1,
                'name'                => 'Vossenjacht',
                'description'         => 'Speurtocht waarbij verklede mensen (vossen) gezocht moeten worden',
                'special_interest_at' => null,
            ],
            45  => [
                'id'                  => 46,
                'is_published'        => 1,
                'name'                => 'Waterschappen',
                'description'         => 'Activiteiten gerelateerd aan waterbeheer en waterschappen in Nederland',
                'special_interest_at' => null,
            ],
            46  => [
                'id'                  => 47,
                'is_published'        => 1,
                'name'                => 'Vluchtelingen',
                'description'         => 'Activiteiten gericht op bewustwording over en hulp aan vluchtelingen',
                'special_interest_at' => null,
            ],
            47  => [
                'id'                  => 48,
                'is_published'        => 1,
                'name'                => 'Rainbowscouting',
                'description'         => 'Activiteiten gericht op LHBTI+ acceptatie binnen scouting',
                'special_interest_at' => null,
            ],
            48  => [
                'id'                  => 49,
                'is_published'        => 1,
                'name'                => 'Gender',
                'description'         => 'Activiteiten rond genderidentiteit en gendergelijkheid',
                'special_interest_at' => null,
            ],
            49  => [
                'id'                  => 50,
                'is_published'        => 1,
                'name'                => 'Homoseksualiteit',
                'description'         => 'Activiteiten gericht op acceptatie en begrip van seksuele diversiteit',
                'special_interest_at' => '2000-10-11',
            ],
            50  => [
                'id'                  => 51,
                'is_published'        => 1,
                'name'                => 'Sociale Veiligheid',
                'description'         => 'Activiteiten gericht op het bevorderen van een veilige sociale omgeving binnen scouting',
                'special_interest_at' => null,
            ],
            51  => [
                'id'                  => 52,
                'is_published'        => 1,
                'name'                => 'Ouder Kind Opkomst',
                'description'         => 'Activiteiten waarbij ouders samen met hun kinderen deelnemen aan een scoutingbijeenkomst',
                'special_interest_at' => null,
            ],
            52  => [
                'id'                  => 53,
                'is_published'        => 1,
                'name'                => 'Duurzame ontwikkelingsdoel 1 Geen armoede',
                'description'         => 'Activiteiten gericht op het bestrijden van armoede wereldwijd',
                'special_interest_at' => null,
            ],
            53  => [
                'id'                  => 54,
                'is_published'        => 1,
                'name'                => 'Duurzame ontwikkelingsdoel 2 Geen honger',
                'description'         => 'Activiteiten gericht op het bestrijden van honger en het bevorderen van voedselzekerheid',
                'special_interest_at' => null,
            ],
            54  => [
                'id'                  => 55,
                'is_published'        => 1,
                'name'                => 'Halloween',
                'description'         => 'Griezelige activiteiten en spellen rond Halloween',
                'special_interest_at' => '2000-10-31',
            ],
            55  => [
                'id'                  => 56,
                'is_published'        => 1,
                'name'                => 'Duurzame ontwikkelingsdoel 8 Eerlijk werk en economische groei',
                'description'         => 'Activiteiten gericht op duurzame economische groei en waardig werk voor iedereen',
                'special_interest_at' => null,
            ],
            56  => [
                'id'                  => 57,
                'is_published'        => 1,
                'name'                => 'Vredeslicht',
                'description'         => 'Activiteiten rond het doorgeven van het vredeslicht in de kerstperiode',
                'special_interest_at' => '2000-12-21',
            ],
            57  => [
                'id'                  => 58,
                'is_published'        => 1,
                'name'                => 'Olympische Spelen',
                'description'         => 'Sportieve activiteiten geïnspireerd op de Olympische Spelen',
                'special_interest_at' => '2000-07-26',
            ],
            58  => [
                'id'                  => 59,
                'is_published'        => 1,
                'name'                => 'Earth Hour',
                'description'         => 'Activiteiten rond de wereldwijde actie waarbij een uur het licht uit gaat voor het klimaat',
                'special_interest_at' => '2000-03-31',
            ],
            59  => [
                'id'                  => 60,
                'is_published'        => 1,
                'name'                => 'Verkiezingen',
                'description'         => 'Activiteiten rond democratie en het verkiezingsproces',
                'special_interest_at' => null,
            ],
            60  => [
                'id'                  => 61,
                'is_published'        => 1,
                'name'                => 'Valentijn',
                'description'         => 'Activiteiten en spellen rond Valentijnsdag',
                'special_interest_at' => '2000-02-14',
            ],
            61  => [
                'id'                  => 62,
                'is_published'        => 1,
                'name'                => 'Pionieren',
                'description'         => 'Activiteiten waarbij constructies worden gebouwd met hout en touw',
                'special_interest_at' => null,
            ],
            62  => [
                'id'                  => 63,
                'is_published'        => 1,
                'name'                => 'Financiële Acties',
                'description'         => 'Activiteiten gericht op het werven van fondsen voor de scoutinggroep',
                'special_interest_at' => null,
            ],
            63  => [
                'id'                  => 64,
                'is_published'        => 1,
                'name'                => 'Complimentendag',
                'description'         => 'Activiteiten rond nationale complimentendag om elkaar positief te waarderen',
                'special_interest_at' => '2000-03-01',
            ],
            64  => [
                'id'                  => 65,
                'is_published'        => 1,
                'name'                => 'Duurzame Ontwikkelingsdoelen',
                'description'         => 'Algemene activiteiten rond de Sustainable Development Goals van de VN',
                'special_interest_at' => null,
            ],
            65  => [
                'id'                  => 66,
                'is_published'        => 1,
                'name'                => 'Zaaien en Kweken',
                'description'         => 'Activiteiten rond het kweken van planten en tuinieren',
                'special_interest_at' => '2000-04-22',
            ],
            66  => [
                'id'                  => 67,
                'is_published'        => 1,
                'name'                => 'Kennismakingsspel',
                'description'         => 'Spellen om elkaar beter te leren kennen binnen de groep',
                'special_interest_at' => '2000-09-01',
            ],
            67  => [
                'id'                  => 68,
                'is_published'        => 1,
                'name'                => 'Sint Joris',
                'description'         => 'Activiteiten rond de scoutingtraditie van Sint Joris en de draak',
                'special_interest_at' => '2000-04-23',
            ],
            68  => [
                'id'                  => 69,
                'is_published'        => 1,
                'name'                => 'Serious Request',
                'description'         => 'Activiteiten gekoppeld aan de landelijke geldinzamelingsactie van 3FM',
                'special_interest_at' => '2000-12-20',
            ],
            69  => [
                'id'                  => 70,
                'is_published'        => 1,
                'name'                => 'Duurzame ontwikkelingsdoel 3 Goede gezondheid en welzijn',
                'description'         => 'Activiteiten gericht op het bevorderen van gezondheid en welzijn voor iedereen',
                'special_interest_at' => null,
            ],
            70  => [
                'id'                  => 71,
                'is_published'        => 1,
                'name'                => 'Holi',
                'description'         => 'Activiteiten rond het kleurrijke Hindoeïstische lentefeest',
                'special_interest_at' => '2000-03-14',
            ],
            71  => [
                'id'                  => 72,
                'is_published'        => 1,
                'name'                => 'IRC Spelen',
                'description'         => 'Activiteiten die gebruik maken van het chatsysteem Internet Relay Chat',
                'special_interest_at' => null,
            ],
            72  => [
                'id'                  => 73,
                'is_published'        => 1,
                'name'                => 'Brainstormen',
                'description'         => 'Technieken en activiteiten om creatief na te denken en ideeën te genereren',
                'special_interest_at' => null,
            ],
            73  => [
                'id'                  => 74,
                'is_published'        => 1,
                'name'                => 'Winter',
                'description'         => 'Activiteiten specifiek geschikt voor de winterperiode',
                'special_interest_at' => '2000-12-21',
            ],
            74  => [
                'id'                  => 75,
                'is_published'        => 1,
                'name'                => 'Communicatie',
                'description'         => 'Activiteiten gericht op verschillende vormen van communicatie en samenwerking',
                'special_interest_at' => null,
            ],
            75  => [
                'id'                  => 76,
                'is_published'        => 1,
                'name'                => 'Weer Naar Buiten',
                'description'         => 'Buitenactiviteiten die stimuleren om de natuur in te gaan',
                'special_interest_at' => null,
            ],
            76  => [
                'id'                  => 77,
                'is_published'        => 1,
                'name'                => 'Harry Potter',
                'description'         => 'Magische activiteiten gebaseerd op de wereld van Harry Potter',
                'special_interest_at' => '2000-05-02',
            ],
            77  => [
                'id'                  => 78,
                'is_published'        => 1,
                'name'                => 'Pesten',
                'description'         => 'Activiteiten gericht op pestpreventie en sociale weerbaarheid',
                'special_interest_at' => '2000-04-19',
            ],
            78  => [
                'id'                  => 79,
                'is_published'        => 1,
                'name'                => 'Kinderrechten',
                'description'         => 'Activiteiten rond de rechten van kinderen wereldwijd',
                'special_interest_at' => '2000-11-20',
            ],
            79  => [
                'id'                  => 80,
                'is_published'        => 1,
                'name'                => 'Keti Koti',
                'description'         => 'Activiteiten rond de viering van de afschaffing van de slavernij',
                'special_interest_at' => '2000-07-01',
            ],
            80  => [
                'id'                  => 81,
                'is_published'        => 1,
                'name'                => 'Sint Maarten',
                'description'         => 'Activiteiten rond het feest van Sint Maarten op 11 november',
                'special_interest_at' => '2000-11-11',
            ],
            81  => [
                'id'                  => 82,
                'is_published'        => 1,
                'name'                => 'Herfst',
                'description'         => 'Activiteiten specifiek geschikt voor de herfstperiode',
                'special_interest_at' => '2000-09-23',
            ],
            82  => [
                'id'                  => 83,
                'is_published'        => 1,
                'name'                => 'Buitenspeeldag',
                'description'         => 'Activiteiten voor de nationale buitenspeeldag',
                'special_interest_at' => '2000-06-11',
            ],
            83  => [
                'id'                  => 84,
                'is_published'        => 1,
                'name'                => 'Scouting 2025',
                'description'         => 'Activiteiten gericht op de toekomstvisie van Scouting Nederland',
                'special_interest_at' => null,
            ],
            84  => [
                'id'                  => 85,
                'is_published'        => 1,
                'name'                => 'Renspelletjes',
                'description'         => 'Actieve spellen waarbij rennen centraal staat',
                'special_interest_at' => null,
            ],
            85  => [
                'id'                  => 86,
                'is_published'        => 1,
                'name'                => 'Escape Room',
                'description'         => 'Puzzel- en ontsnappingsactiviteiten in escape room stijl',
                'special_interest_at' => null,
            ],
            86  => [
                'id'                  => 87,
                'is_published'        => 1,
                'name'                => 'Tip van de Maand',
                'description'         => 'Handige tips en trucs voor scoutingactiviteiten',
                'special_interest_at' => null,
            ],
            87  => [
                'id'                  => 88,
                'is_published'        => 1,
                'name'                => 'Duurzame ontwikkelingsdoel 11  Duurzame steden en gemeenschappen',
                'description'         => 'Activiteiten gericht op duurzame en leefbare steden en gemeenschappen',
                'special_interest_at' => null,
            ],
            88  => [
                'id'                  => 89,
                'is_published'        => 1,
                'name'                => 'Sprookjes',
                'description'         => 'Activiteiten gebaseerd op bekende sprookjes en verhalen',
                'special_interest_at' => null,
            ],
            89  => [
                'id'                  => 90,
                'is_published'        => 1,
                'name'                => 'Lente',
                'description'         => 'Activiteiten specifiek geschikt voor de lenteperiode',
                'special_interest_at' => '2000-03-21',
            ],
            90  => [
                'id'                  => 91,
                'is_published'        => 1,
                'name'                => 'Denkdag',
                'description'         => 'Activiteiten rond de internationale scoutingdag voor denken aan anderen (Engels: Thinking Day) op 22 februari',
                'special_interest_at' => '2000-02-22',
            ],
            91  => [
                'id'                  => 92,
                'is_published'        => 1,
                'name'                => 'Duurzame ontwikkelingsdoel 17 Partnerschap om doelstellingen te bereiken',
                'description'         => 'Activiteiten gericht op samenwerking voor duurzame ontwikkeling',
                'special_interest_at' => null,
            ],
            92  => [
                'id'                  => 93,
                'is_published'        => 1,
                'name'                => 'Duurzame ontwikkelingsdoel 6 Schoon water en sanitair',
                'description'         => 'Activiteiten gericht op toegang tot schoon water en goede sanitaire voorzieningen',
                'special_interest_at' => null,
            ],
            93  => [
                'id'                  => 94,
                'is_published'        => 1,
                'name'                => 'Werken met Ploegen',
                'description'         => 'Activiteiten gericht op samenwerken met je subgroep bij de scouts',
                'special_interest_at' => null,
            ],
            94  => [
                'id'                  => 95,
                'is_published'        => 1,
                'name'                => 'Duurzame ontwikkelingsdoel 9 Industrie, innovatie en infrastructuur',
                'description'         => 'Activiteiten gericht op duurzame industrie en innovatie',
                'special_interest_at' => null,
            ],
            95  => [
                'id'                  => 96,
                'is_published'        => 1,
                'name'                => 'Zomer',
                'description'         => 'Activiteiten specifiek geschikt voor de zomerperiode',
                'special_interest_at' => '2000-06-21',
            ],
            96  => [
                'id'                  => 97,
                'is_published'        => 1,
                'name'                => 'Wedstrijdzeilen',
                'description'         => 'Activiteiten rond zeilwedstrijden en competitief zeilen',
                'special_interest_at' => '2000-05-30',
            ],
            97  => [
                'id'                  => 98,
                'is_published'        => 1,
                'name'                => 'Sneeuw',
                'description'         => 'Activiteiten die je kunt doen in de sneeuw',
                'special_interest_at' => '2000-02-01',
            ],
            98  => [
                'id'                  => 99,
                'is_published'        => 1,
                'name'                => 'Installatie',
                'description'         => 'Activiteiten rond de officiële installatie van nieuwe scouts',
                'special_interest_at' => '2000-10-01',
            ],
            99  => [
                'id'                  => 100,
                'is_published'        => 1,
                'name'                => 'Veiligheid',
                'description'         => 'Activiteiten gericht op fysieke en sociale veiligheid binnen scouting',
                'special_interest_at' => null,
            ],
            100 => [
                'id'                  => 101,
                'is_published'        => 1,
                'name'                => 'Jungle Book of Records',
                'description'         => 'Activiteiten gebaseerd op het behalen van records in jungleboek-thema geïntroduceerd tijdens het 100 jaar welpen feest',
                'special_interest_at' => null,
            ],
            101 => [
                'id'                  => 102,
                'is_published'        => 1,
                'name'                => 'Elfstedentocht',
                'description'         => 'Activiteiten geïnspireerd op de traditionele Friese Elfstedentocht',
                'special_interest_at' => '2000-01-04',
            ],
            102 => [
                'id'                  => 103,
                'is_published'        => 1,
                'name'                => 'Vuur',
                'description'         => 'Activiteiten rond het veilig maken en gebruiken van vuur',
                'special_interest_at' => null,
            ],
            103 => [
                'id'                  => 104,
                'is_published'        => 1,
                'name'                => 'Regiospelen',
                'description'         => 'Activiteiten en wedstrijden tussen scoutinggroepen in de regio',
                'special_interest_at' => null,
            ],
            104 => [
                'id'                  => 105,
                'is_published'        => 1,
                'name'                => 'Pride',
                'description'         => 'Activiteiten rond LHBTI+ acceptatie en Pride-vieringen',
                'special_interest_at' => '2000-06-01',
            ],
            105 => [
                'id'                  => 106,
                'is_published'        => 1,
                'name'                => 'Last Minute Box',
                'description'         => 'Kant-en-klare activiteiten voor als je programma onverwacht moet aanpassen',
                'special_interest_at' => null,
            ],
            106 => [
                'id'                  => 107,
                'is_published'        => 1,
                'name'                => 'Braille',
                'description'         => 'Activiteiten die te maken hebben met braille',
                'special_interest_at' => '2000-01-04',
            ],
            107 => [
                'id'                  => 108,
                'is_published'        => 1,
                'name'                => 'Monopoly',
                'description'         => 'Activiteiten met een twist en knipoog naar het bekende spel Monopoly',
                'special_interest_at' => '2000-03-19',
            ],
        ]);
    }
}
